### ISSUE TITLE
Module fails to load in Foundry v10

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy5e-sheet#545]
In Foundry v10, the module fails to load.  The server spits out the following error...

```
FoundryVTT | 2022-07-26 15:31:21 | [error] Metadata validation failed for module "tidy5e-sheet": The file "../fonts/modesto-condensed/modesto-condensed.css" included by module tidy5e-sheet does not exist
Error: Metadata validation failed for module "tidy5e-sheet": The file "../fonts/modesto-condensed/modesto-condensed.css" included by module tidy5e-sheet does not exist
    at PackageAssetField.initialize (file:///home/alan/foundry-10/resources/app/dist/packages/package.mjs:1:1262)
    at file:///home/alan/foundry-10/resources/app/common/data/fields.mjs:853:40
    at Array.map (<anonymous>)
    at SetField.initialize (file:///home/alan/foundry-10/resources/app/common/data/fields.mjs:853:18)
    at SetField.initialize (file:///home/alan/foundry-10/resources/app/common/data/fields.mjs:904:26)
    at Module._initialize (file:///home/alan/foundry-10/resources/app/common/abstract/data.mjs:203:27)
    at Module._initialize (file:///home/alan/foundry-10/resources/app/dist/packages/package.mjs:1:2903)
    at new DataModel (file:///home/alan/foundry-10/resources/app/common/abstract/data.mjs:56:10)
    at new BasePackage (file:///home/alan/foundry-10/resources/app/common/packages/base-package.mjs:59:5)
    at new BaseModule (file:///home/alan/foundry-10/resources/app/common/packages/base-module.mjs:11:16)
```

**Comment by sdenec** [comment]
v10 update released :)
