### ISSUE TITLE
Rolling an item from the favourites tab throws an error

### ISSUE THREAD

**Issue by tposney** [sdenec/tidy5e-sheet#565]
```
Uncaught TypeError: app._onItemRoll is not a function
[Detected 1 package: tidy5e-sheet]
    at HTMLDivElement.<anonymous> (tidy5e-favorites.js:317:55)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous) @ tidy5e-favorites.js:317
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
I had a look and dnd5e 2.0.1 changes the call to 
``app._onItemUse `` and unlike ``item.roll`` the did not wrap  ``_onItemRoll`` to ``_onItemUse``

**Comment by sdenec** [comment]
Fantastic find! Thank you for your help:)
