### ISSUE TITLE
[BUG] Swashbuckler Initiative ends up with NaN in mod

### ISSUE THREAD

**Issue by etriebe** [sdenec/tidy5e-sheet#714]
**Module Version:** v0.8.22

Log file: [swashbuckler-1677046443884.log](https://github.com/sdenec/tidy5e-sheet/files/10800571/swashbuckler-1677046443884.log)

**Describe the bug**
D&D 5e Rogue Swashbuckler subclass initiative is broken when Tidy5e sheet is enabled. 

**To Reproduce**
1. D&D Beyond import a character that is a swashbuckler of at least 3rd level
2. Create a combat with that character
3. Attempt to roll initiative for the character

After Import from D&D Beyond it looks correct:
![image](https://user-images.githubusercontent.com/7503160/220537785-1e45ed79-c6f9-4083-9169-89fd45cddd6f.png)

But there are two errors thrown.

```
Error: Roll.safeEval produced a non-numeric result from expression "NaN"
    at Roll.safeEval (foundry.js:9432:13)
    at simplifyBonus (utils.mjs:17:40)
    at Actor5e._prepareInitiative (actor.mjs:645:23)
    at Actor5e.prepareDerivedData (actor.mjs:169:10)
    at Actor5e.prepareData (foundry.js:13286:10)
    at Actor5e.prepareData (actor.mjs:95:11)
    at Actor5e._safePrepareData (foundry.js:13264:12)
    at Actor5e._initialize (foundry.js:13089:17)
    at Actor5e.reset (commons.js:5437:12)
    at ClientDatabaseBackend._handleDeleteEmbeddedDocuments (foundry.js:12979:12)

Error: Roll.safeEval produced a non-numeric result from expression "NaN"
    at Roll.safeEval (foundry.js:9432:13)
    at simplifyBonus (utils.mjs:17:40)
    at Actor5e._prepareInitiative (actor.mjs:645:23)
    at Actor5e.prepareDerivedData (actor.mjs:169:10)
    at Actor5e.prepareData (foundry.js:13286:10)
    at Actor5e.prepareData (actor.mjs:95:11)
    at Actor5e._safePrepareData (foundry.js:13264:12)
    at Actor5e._initialize (foundry.js:13089:17)
    at Actor5e.updateSource (commons.js:5586:12)
    at ClientDatabaseBackend._postUpdateDocumentCallbacks (foundry.js:12831:11)
```
And then after attempting to roll initiative it shows up on the sheet as NaN
![image](https://user-images.githubusercontent.com/7503160/220537864-04551829-ba3b-43a3-b786-ef79153450dd.png)
foundry.js:11730 
        
       Uncaught (in promise) Error: Unresolved StringTerm NaN requested for evaluation
    at StringTerm.evaluate (foundry.js:11730:11)
    at D20Roll._evaluate (foundry.js:9292:42)
    at async Combat.rollInitiative (foundry.js:18659:7)
    at async Actor5e.rollInitiative (foundry.js:16616:5)
    at async Actor5e.rollInitiative (actor.mjs:1542:20)
    at async Actor5e.rollInitiativeDialog (actor.mjs:1525:5)

**Expected behavior**
Initiative to happen with the extra modifier and for it to be a number. 

**Browser:**
Edge Version 110.0.1587.50 (Official build) (64-bit)

**Foundry Version:** 
10.291

**Game System:** 
D&D 5e 2.1.5

**Comment by p4535992** [comment]
Did you confirm the issue is not present on the default sheet ?

**Comment by MrPrimate** [comment]
@p4535992 I can confirm this is the case

**Comment by etriebe** [comment]
Yeah. Not present with default sheet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by p4535992** [comment]
Can you export the actor and pass to me ?

**Comment by etriebe** [comment]
Both exported for with and without tidy5e enabled..

[tidy5e_off_fvtt-Actor-gaunt-_whisper_-galondel.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10806335/tidy5e_off_fvtt-Actor-gaunt-_whisper_-galondel.json.txt)
[tidy5e_on_fvtt-Actor-gaunt-_whisper_-galondel.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10806336/tidy5e_on_fvtt-Actor-gaunt-_whisper_-galondel.json.txt)

**Comment by p4535992** [comment]
i will add a patch on the next release, but i didn't  get the issue origin

**Comment by LususNaturae77** [comment]
I am still getting this error on 0.8.35

[without-tidy-fvtt-Actor-dawn-hythenos.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10947507/without-tidy-fvtt-Actor-dawn-hythenos.json.txt)
[with-tidy-fvtt-Actor-dawn-hythenos.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10947508/with-tidy-fvtt-Actor-dawn-hythenos.json.txt)

**Comment by MrPrimate** [comment]
> I am still getting this error on 0.8.35
> 
> [without-tidy-fvtt-Actor-dawn-hythenos.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10947507/without-tidy-fvtt-Actor-dawn-hythenos.json.txt)
> [with-tidy-fvtt-Actor-dawn-hythenos.json.txt](https://github.com/sdenec/tidy5e-sheet/files/10947508/with-tidy-fvtt-Actor-dawn-hythenos.json.txt)
> 

You will have to manually change the value from NaN once you've upgraded (or if using DDB Importer reimport) to get the value back

**Comment by LususNaturae77** [comment]
Both of these are after import. I will say, the Initiative value is being set to Dex instead of NaN. It's just the Cha bonus to Initiative that is lost (or Int bonus in this character's case)

**Comment by LususNaturae77** [comment]
Manually adding the bonus back with Tidy5e does work, but re-importing will set set the bonus back to 0.

**Comment by kgar** [comment]
While working on the Tidy 5e Sheets rewrite, I got curious about this issue. I think it's happening because the initiative mod input uses a maxlenth of 2. This results in "+ 3" eventually reprocessing into "+ ", and then, it reprocesses into NaN. It's a little late, I know, but if we were to take the maxlength off of the ini mod input, it would not truncate and sabotage ini mods longer than 2 characters.

**Comment by kgar** [comment]
Hey, it's me 3 weeks later. I'm submitting a fix for this.
