### ISSUE TITLE
Player sheets do not work on dnd 2.4.0[BUG]

### ISSUE THREAD

**Issue by stalker168** [sdenec/tidy5e-sheet#797]
**Module Version:** v0.9.18

**Without debugging enabled**
```
TypeError: An error occurred while rendering Tidy5eSheet 144. Cannot read properties of undefined (reading 'label')
    at _Tidy5eSheet.getData (character-sheet.mjs:42:43)
    at async _Tidy5eSheet.getData (tidy5e-sheet.js:70:21)
    at async _Tidy5eSheet._render (foundry.js:5753:18)
    at async _Tidy5eSheet._render (foundry.js:6473:5)
```
**With debugging enabled**
```
Error: An error occurred while rendering Tidy5eSheet 144. One of original or other are not Objects!
    at mergeObject (commons.js:2734:13)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at Object.mergeObject (commons.js:2755:41)
    at _Tidy5eSheet._render (foundry.js:5748:19)
    at _Tidy5eSheet._render (foundry.js:6473:17)
    at _Tidy5eSheet.render (foundry.js:5710:10)
    at _Tidy5eSheet.render (foundry.js:7052:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁ActorSheet.prototype.render#item-piles (libwrapper.js:50:16)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ActorSheet.prototype.render#0 (libWrapper-wrapper.js:189:20)
    at Token5e._onClickLeft2 (foundry.js:56159:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Token.prototype._onClickLeft2#item-piles (libwrapper.js:14:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onClickLeft2#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:31680:17)
    at #handleClickLeft2 (foundry.js:31885:15)
    at #handleMouseDown (foundry.js:31852:83)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)
```
**To Reproduce**
Player sheets do not open at all.

**Foundry Version:** 
v11.309
**Game System:** 
dnd5e v2.4.0

**Comment by Zanfii** [comment]
This is an issue with 5e changing stuff it seems, not this module itself

It's discussed here with a fix that works for me
https://github.com/foundryvtt/dnd5e/issues/2606#issuecomment-1817058000

> Not a real solution but I made a temporary fix with changing the offending line (`18322`) in `dnd5e.mjs` to
`type: context.system.details?.type?.label ?? context.system.details.race`

**Comment by kgar** [comment]
I've submitted 2.4.0 compatibility updates for Tidy 5e Sheets, but other modules may also be experiencing issues.
After these fixes are released in a new version, try opening the sheets with no other modules open and see if they work.
